# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('home_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('work_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail Address')),
                ('gender', models.SmallIntegerField(choices=[(0, 'Not Known'), (1, 'Male'), (2, 'Female'), (9, 'Not Applicable')], default=0)),
            ],
            options={
                'ordering': ('last_name',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.SmallIntegerField(choices=[(0, 'Not Known'), (1, 'Male'), (2, 'Female'), (9, 'Not Applicable')], default=0)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail Address')),
                ('home_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('work_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('contact_relation', models.CharField(choices=[('unknown', 'Unknown'), ('parent', 'Parent'), ('guardian', 'Guardian'), ('family', 'Family'), ('other', 'Other')], default='unknown', max_length=10)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Contact')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
            ],
            options={
                'ordering': ('last_name',),
            },
        ),
    ]
