# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-14 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('home_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('work_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail Address')),
                ('dob', models.DateField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School')),
            ],
            options={
                'ordering': ('-last_name',),
            },
        ),
    ]
