# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-14 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('last_name',)},
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, 'Not Known'), (1, 'Male'), (2, 'Female'), (9, 'Not Applicable')], default=0),
        ),
    ]
