# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-14 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20160914_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('home_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('work_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail Address')),
                ('gender', models.SmallIntegerField(choices=[(0, 'Not Known'), (1, 'Male'), (2, 'Female'), (9, 'Not Applicable')], default=0)),
            ],
            options={
                'ordering': ('last_name',),
            },
        ),
        migrations.AddField(
            model_name='student',
            name='contact_relation',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Contact'),
        ),
    ]
