# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-14 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20160914_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact_relation',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('parent', 'Parent'), ('guardian', 'Guardian'), ('family', 'Family'), ('other', 'Other')], default='unknown', max_length=10),
        ),
    ]
