# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-14 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20160914_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='fax',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='school',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='school',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
