# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-15 13:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20160914_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
